name: ecommerece
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.5
  intl: ^0.18.1
  get: ^4.6.5
  shared_preferences: ^2.1.1
  flutter_otp_text_field: ^1.1.1
  dartz: ^0.10.1
  http: ^0.13.6
  firebase_core: ^2.13.1
  firebase_messaging: ^14.6.2
  cached_network_image: ^3.2.3
  velocity_x: ^4.1.0
  carousel_slider: 
  flutter_staggered_animations: ^1.1.1
  google_maps_flutter: ^2.3.0
  internet_connection_checker: ^1.0.0+1
  mysql1: ^0.20.0
  # connectivity: ^3.0.6
  # fluttertoast: ^8.2.2
  # like_button: ^2.0.5
  # flash: ^3.0.5+1
  # connectivity: ^3.0.6
  # fluttertoast: ^8.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  - family: Cairo
    fonts:
      - asset: assets/fonts/Cairo/Cairo-Regular.ttf
      - asset: assets/fonts/Cairo/Cairo-Bold.ttf
        weight: 600
      
  - family: Lato
    fonts:
      - asset: assets/fonts/Lato/Lato-Regular.ttf
      - asset: assets/fonts/Lato/Lato-Bold.ttf
        weight: 700
      
  
  # fonts:
  #   - family: Cairo
  #     fonts:
  #       - asset: assets/fonts/Cairo/Cairo-Regular.ttf
  #       - asset: assets/fonts/Cairo/Cairo-Bold.ttf
  #         weight: 700
    
 
  #   - family: Lato
  #     fonts:
  #       - asset: assets/fonts/Lato/Lato-Regular.ttf
  #       - asset: assets/fonts/Cairo/Lato-Bold.ttf
  #         weight: 700
  #   - family: Anton
  #     fonts:
  #       - asset: assets/fonts/Lato/Anton-Regular.ttf.ttf
          
  #       Anton-Regular.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
